### ISSUE TITLE
利用規約ページを追加（ページだけ）

### ISSUE THREAD

**Issue by aiandrox** [runteq/fledge-hub#167]
## 概要

`/terms`で利用規約ページにアクセスできるようにする

利用規約の中身は書かなくていい。

- ログインしているユーザーもログインしていないユーザーも閲覧可能
- 新規登録ページのリンクから遷移できるようにする

ちゃんとアクセスできることを確かめるテストも書いてくれると嬉しい！

**Comment by akitoshi-m** [comment]
`/users/new` はなかったので `/registrations/new` だと解釈して作成します！
