### ISSUE TITLE
利用規約・プライバシーポリシーの追加

### ISSUE THREAD

**Issue by aiandrox** [runteq/fledge-hub#91]
## 概要

現時点ではいらないと思っていますが、必要なら追加してください！（笑）
PR待っています！ｗｗ

**Comment by Mutsuki1102** [comment]
法務レビュー済みの利用規約です。
https://drive.google.com/file/d/1J-OYgOmju9rdmMHeFVG7CKP0TPYliysi/view?usp=sharing

**Comment by Mutsuki1102** [comment]
> [#117 (comment)](https://github.com/runteq/fledge-hub/pull/117#discussion_r642031407)
> このことを書いておいたほうがいいかも
> サービスとして、どのユーザーが登録していたかって残さないほうがいいですかね？

この部分は下記のように利用規約で定義してますー！退会後も個人情報を保有＆利用できるという認識です。

```
2. 当社は、本サービスの提供において取得した個人情報を、FledgeHub会員の同意なく利用目的の範囲を超えて利用しないものとします。当社が取得した個人情報は、下記の目的の範囲内で適正に取り扱うものとします。なお、当社は、本サービスの提供終了後も当該 個人情報を保有および利用することができるものとします。
```
